[repository]
name = "hyev"
authors = ["DreamMaoMao"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "9f1caf4fbbe503359622d3b7f820ebbc06c3d8fa"]
]

[hyev]
description = "hyprland animation sound plugin"
authors = ["DreamMaoMao"]
output = "build/libhyev.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=Release -B build",
	"cmake --build build"
]