[repository]
name = "hyev"
authors = ["DreamMaoMao"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "c71e6cef852b13c12e658524cd25d46be992e73e"]
]

[hyev]
description = "hyprland animation sound plugin"
authors = ["DreamMaoMao"]
output = "build/libhyev.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=Release -B build",
	"cmake --build build -j $(nproc)"
]