[hyev]
description = "hyprland event trigger"
version = "0.1"
author = "DreamMaoMao"

[hyev.build]
output = "build/libhyev.so"
steps = [
  "rm -rf build",
  "cmake -DCMAKE_BUILD_TYPE=Debug -B build",
  "cmake --build build"
]
